### ISSUE TITLE
Color images are messed up in theora transport

### ISSUE THREAD

**Issue by dgossow** [ros-perception/image_transport_plugins#1]
![Screenshot from 2013-01-18 13:13:38](https://f.cloud.github.com/assets/505655/79486/f66b2e8a-61b3-11e2-87c6-c395c46c2525.png)

**Comment by chadrockey** [comment]
This is an RGB to BGR color swap right?  Image color for this topic is fine?

**Comment by dgossow** [comment]
This is how it should look like:

![Screenshot from 2013-01-18 13:15:01](https://f.cloud.github.com/assets/505655/79488/25e0e1b4-61b4-11e2-95ba-faa9d57843f1.png)

**Comment by jkammerl** [comment]
thanks! fixed in 07b7912ab419113f7bbfbe7886ee623632d5befc

**Comment by tnaka** [comment]
Hi,

I encountered the same problem.

message.encoding contains "RGB8" or "BGR8" etc.
So I think it's better to use this.

``` diff
Index: src/theora_publisher.cpp
===================================================================
--- src/theora_publisher.cpp    (revision 40346)
+++ src/theora_publisher.cpp    (working copy)
@@ -130,7 +130,7 @@
   try
   {
     // conversion necessary
-    cv_image_ptr = cv_bridge::toCvCopy(message, sensor_msgs::image_encodings::RGB8);
+    cv_image_ptr = cv_bridge::toCvCopy(message, message.encoding);
   }
   catch (cv::Exception& e)
   {
```

**Comment by jkammerl** [comment]
Hi Tnaka,

later in theora_publisher.cpp, the input image data is assumed to be BGR encoded .

// Convert image to Y'CbCr color space used by Theora
  cv::Mat ycrcb;
  cv::cvtColor(bgr_padded, ycrcb, CV_BGR2YCrCb);

Your patch would not fix the wrong color encoding for input images that are encoded with RGB8.

Best, Julius

**Comment by tnaka** [comment]
Hi Julius,

Oh, I had thought that "encoding" of cv_bridge::toCvCopy is the encoding of a source image.
Now I understand that It is the encoding of a copied image.

Thanks for your kind reply.

**Comment by tpet** [comment]
Hi everyone, would it be possible to fix this also in the fuerte? There is the same problem.
