### ISSUE TITLE
Maintenance Handover

### ISSUE THREAD

**Issue by ijnek** [ros-perception/image_transport_plugins#111]
There are many PRs and issues that aren't getting much attention in this repo, despite it being an important package. The maintainers listed in some of the package.xml files have moved on a long time ago.

I'm wondering if I could be added to the maintenance team here? I'm currently the core maintainer of ros-perception/vision_opencv for a similar reason.

Pinging @ivanpauno and @clalancette based off most recent commits.

**Comment by clalancette** [comment]
It is fine by me, but I'm not a maintainer here.

Looking through the current maintainers on the `ros2` branch, it seems to be listed as @mjcarroll @dgossow and @jkammerl .  There is even a PR open to change the maintainer to @stwirth (on the noetic-devel branch, at least): #91 .

For the people listed above, does anyone object to @ijnek taking over maintenance of this repository?

**Comment by mjcarroll** [comment]
Okay with me.

**Comment by ivanpauno** [comment]
I'm not currently a maintainer, but it's fine by me.

**Comment by clalancette** [comment]
All right.  @ijnek I'm going to go ahead and give you write access to this repository.  Feel free to make PRs updating the package.xml to you.

**Comment by ijnek** [comment]
Thanks all, I will create a PR.
