### ISSUE TITLE
Parameter for compressed depth are not set for 16bit images

### ISSUE THREAD

**Issue by kohrt** [ros-perception/image_transport_plugins#12]
In [compressed_depth_publisher.cpp](https://github.com/ros-perception/image_transport_plugins/blob/hydro-devel/compressed_depth_image_transport/src/compressed_depth_publisher.cpp#L82-83) the vector for the encode params is not set correctly for 16 bit images. It is only set, if the input image has 32 bit.

A simple solution would be to move the lines [102-103](https://github.com/ros-perception/image_transport_plugins/blob/hydro-devel/compressed_depth_image_transport/src/compressed_depth_publisher.cpp#L102-103) in front of the if statement, so that the params are set for both cases.

Best regards,
Thiemo

**Comment by vrabaud** [comment]
thx for reporting !
