### ISSUE TITLE
Problem to use the image transport compressed plugin

### ISSUE THREAD

**Issue by Cavalletta98** [ros-perception/image_transport_plugins#121]
Hi, i'm trying to compres an image publish on a topic but i'm getting this error when i run this command `rosrun image_transport republish raw in:=/webcam/image_raw compressed out:=/webcam/image_compressed`:

[ERROR] [1671541709.318842973]: OpenCV(4.6.0-dev) /home/pi/opencv/opencv/modules/imgcodecs/src/loadsave.cpp:1145: error: (-2:Unspecified error) in function 'bool cv::imencode(const String&, cv::InputArray, std::vector<unsigned char>&, const std::vector<int>&)'
> Encoding 'params' must be key-value pairs:
>     '(params.size() & 1) == 0'
> where
>     'params.size()' is 9

Can someone please help me?

**Comment by peci1** [comment]
You're probably using a custom-built OpenCV version that is too new for this package. Please, use the version of OpenCV distributed by your operating system (you can build it yourself to get better optimizations, but it should be the same version as the one provided by the OS).

**Comment by Cavalletta98** [comment]
Yes i did as you suggested. Thanks
