### ISSUE TITLE
If you already have a compressed image, is there any use in using image_transport?

### ISSUE THREAD

**Issue by Hommus** [ros-perception/image_transport_plugins#138]
1. If you already have a compressed image, is there any use in using image_transport?
2. Can you pass a compressed image to image_transport?

**Comment by ijnek** [comment]
Personally, I haven't tried this feature, but yes, you should be able to do this by following -  [__4. Publishing compressed images directly__ ](http://wiki.ros.org/compressed_image_transport)

**Comment by Hommus** [comment]
Thanks @ijnek!
You might want to update that link as well, it has an extra full stop on the end, making it an invalid link.
