### ISSUE TITLE
How to compress topic with best_effort qos reliability?

### ISSUE THREAD

**Issue by rafal-gorecki** [ros-perception/image_transport_plugins#157]
Hello, 
I'd like to compress camera topic with `QoS profile:  Reliability: BEST_EFFORT`. Using `ros2 run image_transport republish raw theora` command. Is there some way to do this?

**Comment by ijnek** [comment]
Hi @rafal-gorecki , your question is more appropriate for [ros-perception/image_common](https://github.com/ros-perception/image_common) where image_transport package resides. To my understanding this feature is on its way, with recent efforts such as https://github.com/ros-perception/image_common/pull/288.

Closing as not planned, please consider re-opening this issue over at image_common.
