### ISSUE TITLE
Raspberry pi VIDIOC_QBUF Error

### ISSUE THREAD

**Issue by husdo** [ros-perception/image_transport_plugins#18]
I've tried to install the image_trasport_plugin to a raspberry pi. The aim is to record images from a camera and send down the frames to an other computer.
The raw image topic and the image sending worked, but very slowly.
After the installation I got that error message: [ERROR] [1435317668.655980953]: VIDIOC_QBUF error 19, No such device

Regards: husdo

**Comment by husdo** [comment]
The problem is solved. I have changed the power supply from 1A to 2A. With that change the error message disappeared.
Sorry to bother.

**Comment by vrabaud** [comment]
fastest image_transport_plugin bug fix :)
