### ISSUE TITLE
Why are there build_depends for the metapackage?

### ISSUE THREAD

**Issue by cottsay** [ros-perception/image_transport_plugins#3]
Is there a particular reason that there are build_depends for the image_transport_plugins metapackage? I haven't seen any other metapackages have ANY build depends at all...

**Comment by jkammerl** [comment]
Thanks for reporting this. You are right, the meta package shouldn't contain build_depends. This is now fixed in https://github.com/ros-perception/image_transport_plugins/commit/b0577a9a4fe31ada74d6c97daff7bc290000f965
