### ISSUE TITLE
theora_image_transport publish rate slows down with theora subscriber

### ISSUE THREAD

**Issue by bgoldfai** [ros-perception/image_transport_plugins#5]
I am using a `camera1394_nodelet` and `camera1394` node to publish images from a Point Grey Grasshopper Express. I run the following command: 

```
rosrun camera1394 camera1394_node _video_mode:=format7_mode1 _iso_speed:=400
```

Using `image_view` to look at the raw or compressed transports I get (512x512) images at 115hz, If I switch to the theora transport, the publish rate drops to 61Hz using both the node and nodelet publishers.

**Comment by dgossow** [comment]
Sorry for not getting back to this earlier.

This does not sound like a bug - the theora transport uses a video compression which is pretty cpu intensive, so it doesn't surprise me that the publish rate goes down.

**Comment by bgoldfai** [comment]
CPU usage does increase compared to when I use raw or compressed transport and I was not sure if having a theora subscriber should cause the publish rate of all images from the camera to slow so much. 

I'll close the issue then if you don't believe this is an actual bug.

**Comment by jkammerl** [comment]
You should definitely see an increase in CPU usage when using the theora subscriber. Video compression is computational expensive and it often occupies a full CPU core.
