### ISSUE TITLE
Regression in compressed_depth_image_transport with old bagfiles (Unsupported image format: 16UC1; compressedDepth)

### ISSUE THREAD

**Issue by tlind** [ros-perception/image_transport_plugins#63]
I'm experiencing problems with existing rosbags, when trying to republish compressed depth image messages. The regression is caused by commit a710d4abab2 in 1.14.0 (ROS Noetic) which introduced the new RVL depth compression.

The error message is:

    Unsupported image format: "16UC1; compressedDepth"

and occurs in:

    compressed_depth_image_transport::decodeCompressedDepthImage()

The check for the old format introduced in that commit is not able to match the above format string: https://github.com/ros-perception/image_transport_plugins/blob/73824bc29447a76897bcf58247e260ef43a315aa/compressed_depth_image_transport/src/codec.cpp#L72-L89

This bug might have been introduced due to the badly maintained documentation of the format field (#56).

**Comment by tlind** [comment]
I have added a tiny pull request (#64) that should address this issue.

**Comment by matemat13** [comment]
Just hit this bug today when replaying some old rosbag. Can we pls merge the related PR? In any case - thanks a lot for the fix :)

**Comment by Sanic** [comment]
Thanks for the fix @tlind ! We also had the same problem.

@mjcarroll I was just wondering if there is already a deb package build scheduled for a new version (v1.x) which contains this fix?
