### ISSUE TITLE
Jpeg subscriber: gray decompression only

### ISSUE THREAD

**Issue by cedricpradalier** [ros-perception/image_transport_plugins#8]
Hi, 

I'd like to add a parameter to the Jpeg subscriber to decide if I want to subscribe to the gray-level version of an image, independently of its original color. This would just require to expose the flag in cv::imdecode, to let the use specify something different than CV_LOAD_IMAGE_UNCHANGED.

The rationale for that: I have a webcam publishing jpegs, which I publish directly as a compressed topic. For data logging, they have to stay in color, however for any on-board processing, I need gray. Currently, the image are decompressed to BGR, which involves a conversion from YCbCr, and then a conversion from BGR to gray. Given that Y is the gray value, converting directly to gray from YCbCr would make more sense on my embedded system. 
The OpenCV JpegDecoder seems able to deal with this case and call YCbCr2Gray conversion if needed. 

The untested implementation, for fuerte (my embedded system runs fuerte), is available at https://github.com/cedricpradalier/image_transport_plugins

Once tested on my platform, I can make a merge request if there is any interest.

Thanks and regards

**Comment by vrabaud** [comment]
please make a pull request yes.

**Comment by cedricpradalier** [comment]
We'll do.
I'll check first if the patch still works.

## 

Cedric, mobile, big-thumbed and concise

**Comment by cedricpradalier** [comment]
If I did everything right, the merge request for the fuerte and indigo
version should be in.

On Sat, Apr 25, 2015 at 3:40 PM, Cedric Pradalier <
cedric.pradalier@gmail.com> wrote:

> We'll do.
> I'll check first if the patch still works.
> 
> ## 
> 
> Cedric, mobile, big-thumbed and concise
> On Apr 25, 2015 2:38 PM, "Vincent Rabaud" notifications@github.com
> wrote:
> 
> > please make a pull request yes.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/ros-perception/image_transport_plugins/issues/8#issuecomment-96192079
> > .

## 

Cedric Pradalier

**Comment by vrabaud** [comment]
fixed through #17
